### ISSUE TITLE
task uitest does not use firefox

### ISSUE THREAD

**Issue by Kubiac** [selenide-examples/hangman#5]
I had errors because i didn't have chrome installed. But so I could find out that even uitest uses the chrome driver.
I also checked the code and could find a place where the systemProperty that is set in build.gradle is read again.
I'm very interested in firefox uitests and am just getting started with this demo. So I would very much appreciate a fix.

Best regards

**Comment by asolntsev** [comment]
Hi @Kubiac!
Thank you for reporting the problem. It was a very old problem, indeed. :)

I have fixed it so that we have 3 tasks with explicit names now:
* `./gradlew uitest_firefox`
* `./gradlew uitest_chrome`
* `./gradlew uitest_edge`
